In [ ]:
#1. Write a Python Program to Add Two Matrices?


In [9]:
import numpy as np
a = [[1,3,5],
    [7,9,11],
    [13,15,17]]
b = [[19,21,23],
    [25,27,29],
    [31,33,35]]
 
result = np.array(a) + np.array(b)
print(result)

[[20 24 28]
 [32 36 40]
 [44 48 52]]


In [ ]:
#2. Write a Python Program to Multiply Two Matrices?


In [10]:
import numpy as np
a = [[1,3,5],
    [7,9,11],
    [13,15,17]]
b = [[19,21,23],
    [25,27,29],
    [31,33,35]]
 
result = np.array(a) * np.array(b)
print(result)

[[ 19  63 115]
 [175 243 319]
 [403 495 595]]


In [ ]:
#3. Write a Python Program to Transpose a Matrix?


In [13]:
import numpy as np
a = [[1,3,5],
    [7,9,11],
    [13,15,17]]
result=np.transpose(a)
print(result)

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


In [12]:
#4. Write a Python Program to Sort Words in Alphabetic Order?

In [ ]:
txt= input("Enter any text, will sort it by words: ")
words = [txt.lower() for txt in txt.split()]
words.sort()

print (words)

In [ ]:
#5. Write a Python Program to Remove Punctuation From a String?

In [16]:
import string
a_string = input("Enter any text, will remove punctuation: ")
new_string = a_string.translate(str.maketrans('', '', string.punctuation))

print(new_string)

Enter any text, will remove punctuation: Hello, Good Morning; Have a nice day!!
Hello Good Morning Have a nice day
